version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: foods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2128

  spring-app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/foods
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2128
    depends_on:
      - postgres-db
